### ISSUE TITLE
Is it compatible with node 6?

### ISSUE THREAD

**Issue by andruhon** [xdenser/node-firebird-libfbclient#61]
Trying to build with node 6.2.2

Having the following output (not full one):
`

> firebird@0.0.13 install C:\l\node-firebird-libfbclient
> node-gyp rebuild

CLINK C:\l\node-firebird-libfbclient>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fb-bindings.cc
  fb-bindings-blob.cc
  fb-bindings-fbresult.cc
  fb-bindings-connection.cc
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(326): error C2995: 'v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)': function template has already been defined (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
  C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(319): note: see declaration of 'Nan::imp::NanEnsureHandleOrPersistent' (compiling source file ..\src\fb-bindings.cc)
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(326): error C2995: 'v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)': function template has already been defined (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(346): error C2995: 'v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T> &)': function template has already been defined (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
  C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(319): note: see declaration of 'Nan::imp::NanEnsureHandleOrPersistent' (compiling source file ..\src\fb-bindings-connection.cc)
  C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(334): note: see declaration of 'Nan::imp::NanEnsureLocal' (compiling source file ..\src\fb-bindings.cc)
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(346): error C2995: 'v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T> &)': function template has already been defined (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
  C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(334): note: see declaration of 'Nan::imp::NanEnsureLocal' (compiling source file ..\src\fb-bindings-connection.cc)
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(560): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
  c:\users\andruhon\.node-gyp\6.2.2\include\node\v8.h(5306): note: see declaration of 'v8::Isolate' (compiling source file ..\src\fb-bindings.cc)
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(560): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(560): error C2065: 'GCEpilogueCallback': undeclared identifier (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
  c:\users\andruhon\.node-gyp\6.2.2\include\node\v8.h(5306): note: see declaration of 'v8::Isolate' (compiling source file ..\src\fb-bindings-connection.cc)
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(561): error C2146: syntax error: missing ')' before identifier 'callback' (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(560): error C2065: 'GCEpilogueCallback': undeclared identifier (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(561): error C2143: syntax error: missing ';' before '{' (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(561): error C2146: syntax error: missing ')' before identifier 'callback' (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(561): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\src\fb-bindings.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(561): error C2143: syntax error: missing ';' before '{' (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(566): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' (compiling source file ..\src\fb-bindings.cc)C:\l\node-firebird-libfbclient\node_modules\nan\nan.h(561): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\src\fb-bindings-connection.cc) [C:\l\node-firebird-libfbclient\build\binding.vcxproj]
`

**Comment by mariuz** [comment]
git version compiles ok with node 6.x (ticket can be closed)

git clone git://github.com/xdenser/node-firebird-libfbclient.git

cd node-firebird-libfbclient/

npm install

.....
make: Leaving directory '/tmp/node-firebird-libfbclient/build'
firebird@0.0.13 /tmp/node-firebird-libfbclient
└── nan@2.4.0 

npm WARN firebird@0.0.13 No license field.
